modules/backoffice/controllers/UserController.php
<?php

namespace app\modules\backoffice\controllers;

use app\components\managers\interfaces\AuthManagerInterface;
use app\components\managers\interfaces\UserGridViewSettingsManagerInterface;
use app\components\managers\interfaces\UserManagerInterface;
use app\models\backoffice\forms\LoginForm;
use app\models\backoffice\forms\RecoveryForm;
use app\models\backoffice\forms\ResetTokenPasswordForm;
use app\models\backoffice\forms\UserForm;
use app\models\Permission;
use app\models\Role;
use app\models\search\UserSearch;
use Yii;
use app\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'recovery', 'recovery-password'],
                        'allow'   => true,
                        'roles'   => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'grid-view-settings', 'profile'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view', 'download'],
                        'allow'   => true,
                        'roles'   => [Permission::BACKOFFICE_USER_VIEW],
                    ],
                    [
                        'actions' => ['create'],
                        'allow'   => true,
                        'roles'   => [Permission::BACKOFFICE_USER_CREATE],
                    ],
                    [
                        'actions' => ['update'],
                        'allow'   => true,
                        'roles'   => [Permission::BACKOFFICE_USER_UPDATE],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow'   => true,
                        'roles'   => [Permission::BACKOFFICE_USER_DELETE],
                    ],
                    [
                        'actions' => ['register'],
                        'allow'   => true,
                        'roles'   => ['?'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete'           => ['POST'],
                    'logout'           => ['POST'],
                    'gridViewSettings' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $loginForm = new LoginForm();
        if ($loginForm->load(\Yii::$app->request->post()) && $loginForm->login()) {
            return $this->goBack();
        }

        $this->layout = 'main-login';
        return $this->render('login', [
            'loginForm' => $loginForm,
            'recoveryForm' => new RecoveryForm(),
        ]);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * @param integer $id
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($id) : User
    {
        if (($user = User::findOne($id)) !== null) {
            return $user;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @return string
     */
    public function actionIndex() : string
    {
        $searchModel = new UserSearch();

        $roles = Role::find()->indexBy('id')->all();

        return $this->render('list', [
            'dataProvider' => $searchModel->search(Yii::$app->request->get()),
            'roles'        => $roles,
            'searchModel'  => $searchModel,
        ]);
    }

    public function actionDownload()
    {
        $searchModel = new UserSearch();

        $roles = Role::find()->indexBy('id')->all();

        return $this->renderPartial('_gridView', [
            'dataProvider' => $searchModel->search(Yii::$app->request->get()),
            'roles'        => $roles,
            'searchModel'  => $searchModel,
            'generate'     => true,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return string
     */
    public function actionView($id) : string
    {
        $user = $this->findModel($id);

        return $this->render('view', [
            'user' => $user,
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete(int $id) : Response
    {
        /** @var UserManagerInterface $userManager */
        $userManager = \Yii::$container->get(UserManagerInterface::class);
        $userManager->changeStatus($this->findModel($id), User::STATUS_LOCKED);
        return $this->redirect(['index']);
    }

    public function actionGridViewSettings()
    {
        /** @var UserGridViewSettingsManagerInterface $gridViewSettingsManager */
        $gridViewSettingsManager = \Yii::$container->get(UserGridViewSettingsManagerInterface::class);
        $route = \Yii::$app->request->post('route');
        $gridId = \Yii::$app->request->post('grid_id');
        $params = \Yii::$app->request->post('params');
        if ($route === null || $gridId === null || $params === null) {
            throw new HttpException(400);
        }
        $settings = $gridViewSettingsManager->setSettings(\Yii::$app->user->getId(), $route, $gridId, $params);
        if ($settings->hasErrors()) {
            throw new HttpException(400);
        }
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $newUser = new User();
        $userForm = UserForm::loadFromUser($newUser);
        if ($userForm->load(Yii::$app->request->post()) && $userForm->save()) {
            return $this->redirect(['view', 'id' => $userForm->id]);
        } else {
            $roles = Role::find()->where(['entity_type' => User::TYPE_BACKOFFICE])->indexBy('id')->all();
            return $this->render('create', [
                'user' => $userForm,
                'roles' => $roles,
            ]);
        }
    }

    /**
     * @return string
     */
    public function actionRegister()
    {
        $newUser = new User();
        $userForm = UserForm::loadFromUser($newUser, User::SCENARIO_REGISTER_USER);
        $newUser->scenario = User::SCENARIO_REGISTER_USER;
        $this->layout = 'main-login';

        if ($userForm->load(Yii::$app->request->post()) && $userForm->save()) {
            return $this->redirect(['login']);
        } else {
            return $this->render('createUser', [
                'user' => $userForm,
            ]);
        }
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);
        $userForm = UserForm::loadFromUser($user);

        if ($userForm->load(Yii::$app->request->post()) && $userForm->save($user)) {
            return $this->redirect(['view', 'id' => $userForm->id]);
        } else {
            $roles = Role::find()->where(['entity_type' => User::TYPE_BACKOFFICE])->indexBy('id')->all();
            return $this->render('update', [
                'user' => $userForm,
                'roles' => $roles,
            ]);
        }
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionProfile()
    {
        $userId = \Yii::$app->user->id;
        $user = $this->findModel($userId);
        $userForm = UserForm::loadFromUser($user);

        if ($userForm->load(Yii::$app->request->post()) && $userForm->save()) {
            return $this->redirect(['/']);
        } else {
            $roles = Role::find()->where(['entity_type' => User::TYPE_BACKOFFICE])->indexBy('id')->all();
            return $this->render('update', [
                'user' => $userForm,
                'roles' => $roles,
            ]);
        }
    }

    public function actionRecovery()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $recoveryForm = new RecoveryForm();
        if ($recoveryForm->load(\Yii::$app->request->post()) && ($token = $recoveryForm->createToken())) {
            \Yii::$app->getSession()->setFlash('login-info', 'Письмо с ссылкой на восстановление пароля отправлено на ' . $recoveryForm->email . ' и действует до ' . date('d.m.Y H:i', $token->ttl));
            return $this->redirect(['login']);
        }

        $this->layout = 'main-login';
        return $this->render('login', [
            'loginForm' => new LoginForm(),
            'recoveryForm' => $recoveryForm,
        ]);
    }

    public function actionRecoveryPassword(string $hash)
    {
        /** @var AuthManagerInterface $authManager */
        $authManager = \Yii::$container->get(AuthManagerInterface::class);
        $passwordResetCode = $authManager->resetPassword($hash);
        if ($passwordResetCode === null) {
            \Yii::$app->getSession()->setFlash('login-error', 'Ссылка устарела');
        }
        $resetPasswordForm = new ResetTokenPasswordForm();
        $resetPasswordForm->load(\Yii::$app->request->post());
        if ($resetPasswordForm->load(\Yii::$app->request->post()) && $resetPasswordForm->save($passwordResetCode)) {
            return $this->redirect(['login']);
        }

        $this->layout = 'main-login';
        return $this->render('recovery', [
            'resetForm' => $resetPasswordForm,

modules/backoffice/views/user/_gridView.php
<?php
/**
 * @var $dataProvider yii\data\ActiveDataProvider
 * @var $searchModel User
 * @var $roles \app\models\Role[]
 * @var $generate bool
 */


use app\models\Permission;
use app\models\User;
use app\widgets\gridView\GridViewWidget;
use yii\helpers\ArrayHelper;

echo GridViewWidget::widget([
    'dataProvider'        => $dataProvider,
    'id'                  => 'users_list',
    'filterModel'         => $searchModel,
    'renderButtons'       => [
        GridViewWidget::RENDER_SETTINGS_BUTTON,
        GridViewWidget::RENDER_DOWNLOAD_BUTTON,
        GridViewWidget::RENDER_PAGE_SIZE,
        GridViewWidget::RENDER_SEARCH_INPUT,
    ],
    'generate'            => $generate,
    'filename'            => 'user_backoffice.csv',
    'appendRouteSettings' => 'backoffice',
    'columns'             => [
        'id',
        'username',
        'email:email',
        [
            'attribute' => 'roleName',
            'value'     => function (User $data) {
                $rolesName = [];
                foreach ($data->usersRoles as $usersRole) {
                    $rolesName[] = $usersRole->role->name;
                }
                return join('<br/>', $rolesName);
            },
            'filter'    => ArrayHelper::map($roles, 'id', 'name'),
        ],
        [
            'attribute' => 'status',
            'filter'    => User::getStatuses(),
            'value'     => function (User $data) {
                return $data->getStatusLabel();
            },
        ],
        [
            'class'    => 'yii\grid\ActionColumn',
            'header'   => 'Действия',
            'template' => '{view} ' .
                (\Yii::$app->user->can(Permission::BACKOFFICE_USER_UPDATE) ? '{update} ' : '')
        ],
    ],
]);

modules/backoffice/views/user/create.php
<?php
/**
 * @var yii\web\View $this
 * @var \app\models\backoffice\forms\UserForm $user
 * @var \app\models\Role[] $roles
 */

$this->title = 'Новый пользователь Backoffice';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">
    <?= $this->render('form/_form', [
        'user' => $user,
        'roles' => $roles,
        'isNewRecord' => true,
    ]) ?>

</div>

modules/backoffice/views/user/createUser.php
<?php
/**
 * @var \yii\web\View $this
 * @var ActiveForm $form
 * @var \app\models\backoffice\forms\UserForm $user
 */

use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];
$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
\app\assets\backoffice\BackofficeLoginAsset::register($this);
\app\assets\AppAsset::register($this);

$message = Yii::$app->session->getFlash('login-info');
?>

<div class="user-create">
    <?= $this->render('form/_formUser', [
        'user' => $user,
        'isNewRecord' => true,
    ]) ?>
</div>

modules/backoffice/views/user/list.php
<?php
/**
 * @var \yii\web\View $this
 * @var User $searchModel
 * @var ActiveDataProvider $dataProvider
 * @var Role[] $roles
 */

use app\models\Role;
use app\models\User;
use app\widgets\actionButton\ActionButtonsWidget;
use app\models\Permission;
use yii\data\ActiveDataProvider;


$this->title = 'Список пользователей Backoffice';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-index">
    <?= $this->render(
        '_gridView',
        [
            'dataProvider' => $dataProvider,
            'searchModel'  => $searchModel,
            'roles'        => $roles,
            'generate'     => false,
        ]
    ); ?>
    <p>
        <?= ActionButtonsWidget::widget([
            'buttons' => [
                [
                    'permission' => Permission::BACKOFFICE_USER_CREATE,
                    'label'      => 'Добавить пользователя',
                    'url'        => ['create'],
                    'options'    => ['class' => 'btn btn-success'],
                ],
            ],
        ]); ?>
    </p>
</div>

modules/backoffice/views/user/login.php
<?php
/**
 * @var \yii\web\View $this
 * @var ActiveForm $form
 * @var \app\models\backoffice\forms\LoginForm $loginForm
 * @var \app\models\backoffice\forms\RecoveryForm $recoveryForm
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Вход';
$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];
$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
\app\assets\backoffice\BackofficeLoginAsset::register($this);
\app\assets\AppAsset::register($this);

$message = Yii::$app->session->getFlash('login-info');
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Bablocloud</b></a>
    </div>
    <div class="login-box-body">
        <div class="toggle" id="loginform">
            <?php if (isset($message)) { ?>
                <p class="description-block bg-success" style="padding-left: 3px; padding-right: 3px"><?= $message ?></p>
            <?php } else { ?>
                <p class="login-box-msg">Выполните вход для использования приложения</p>
            <?php } ?>

            <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

            <?= $form
                ->field($loginForm, 'login', $fieldOptions1)
                ->label(false)
                ->textInput(['placeholder' => $loginForm->getAttributeLabel('login')]) ?>

            <?= $form
                ->field($loginForm, 'password', $fieldOptions2)
                ->label(false)
                ->passwordInput(['placeholder' => $loginForm->getAttributeLabel('password')]) ?>

            <div class="row">
                <div class="col-xs-8">
                    <?= $form->field($loginForm, 'rememberMe')->checkbox() ?>
                    <a class="toggle-button" role="button" id="lostbutt">Забыли пароль?</a>
                    <a role="button" href="<?= \yii\helpers\Url::to(['user/register']) ?>">Зарегистрироваться</a>
                </div>
                <div class="col-xs-4">
                    <?= Html::submitButton('Вход', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="toggle hide" id="lostform">
            <?php $form = ActiveForm::begin(['action' => \yii\helpers\Url::to(['user/recovery'])]) ?>
            <?= $form->field($recoveryForm, 'email')->textInput() ?>
            <button class="toggle-button btn btn-default btn-flat" id="cancbutt">Отмена</button>
            <?= Html::submitButton('Восстановить', ['class' => 'btn btn-primary btn-flat']) ?>
            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>

modules/backoffice/views/user/recovery.php
<?php
/**
 * @var \app\models\backoffice\forms\ResetTokenPasswordForm $resetForm
 */

use yii\bootstrap\ActiveForm;

$message = Yii::$app->session->getFlash('login-error');
?>
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Visa Portal</b></a>
    </div>
    <div class="login-box-body">
        <?php if (isset($message)) { ?>
            <p class="login-box-msg"><?= $message ?></p>
            <div class="text-center">
                <a class="btn btn-default btn-flat" role="button" href="<?= \yii\helpers\Url::to(['login']) ?>">Вернуться
                    на главную</a>
            </div>
        <?php } else { ?>
            <?php $form = ActiveForm::begin() ?>
            <?= $form->field($resetForm, 'password')->textInput(['type' => 'password']) ?>
            <?= $form->field($resetForm, 'passwordConfirmation')->textInput(['type' => 'password']) ?>
            <button class="btn btn-primary btn-flat">Продолжить</button>
            <?php ActiveForm::end() ?>
        <?php } ?>
    </div>
</div>

modules/backoffice/views/user/update.php
<?php
/**
 * @var yii\web\View $this
 * @var \app\models\backoffice\forms\UserForm $user
 * @var \app\models\Role[] $roles
 */

$this->title = 'Редактирование пользователя Backoffice: ' . $user->username;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $user->username, 'url' => ['view', 'id' => $user->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="user-update">
    <?= $this->render('form/_form', [
        'user' => $user,
        'roles' => $roles,
        'isNewRecord' => false,
    ]) ?>
</div>

modules/backoffice/views/user/view.php
<?php
/**
 * @var \yii\web\View $this
 * @var \app\models\User $user
 */

use app\widgets\actionButton\ActionButtonsWidget;
use app\models\Permission;
use yii\widgets\DetailView;


$this->title = $user->username;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
    <?= DetailView::widget([
    'model' => $user,
        'attributes' => [
            'id',
            'surname',
            'name',
            'patronymic',
            'email:email',
            'phone1',
            [
                'attribute' => 'phone2',
                'value' => function(\app\models\User $data) {
                    return $data->phone2 ? ($data->phone2 . ($data->phone2_ext ? ' (доб. ' . $data->phone2_ext . ')' : '')) : '';
                },
            ],
            [
                'attribute' => 'roleName',
                'value' => function(\app\models\User $data) {
                    $rolesName = [];
                    foreach ($data->usersRoles as $usersRole) {
                        $rolesName[] = $usersRole->role->name;
                    }
                    return join('<br/>', $rolesName);
                },
            ],
            [
                'label' => 'Статус',
                'value' => $user->getStatusLabel(),
            ],
            'create_time:datetime',
            'update_time:datetime',
        ],
    ]) ?>
    <p>
        <?= ActionButtonsWidget::widget([
            'buttons' => [
                [
                    'permission' => Permission::BACKOFFICE_USER_UPDATE,
                    'label' => 'Редактировать',
                    'url' => ['update', 'id' => $user->id],
                    'options' => ['class' => 'btn btn-primary'],
                ],
            ]
        ]); ?>
    </p>

</div>